version: "3.8"

services:
  frontend:
    build:
      context: ./client
    networks:
      - my_network
    ports:
      - "5173:5173"

  server:
    build:
      context: ./server
    ports:
      - "8000:8000"
    networks:
      - my_network

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - frontend
      - server

networks:
  my_network:
